In [87]:
%load_ext autoreload
%autoreload 2

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import pdb
from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical
from keras import backend as K
from matplotlib import pyplot as plt
%matplotlib inline
import scipy
from scipy import misc, ndimage
from scipy.ndimage.interpolation import zoom
from scipy.ndimage import imread
import helpers
from models import DaveModel, DaveVGG, DaveVGG19, SimpleModel, LeNetModel, BestModel
from trainer import Trainer
from labeller import PseudoLabeller

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [88]:
train = pd.read_json("_RawData/train.json/data/processed/train.json")
test = pd.read_json("_RawData/test.json/data/processed/test.json")

X = helpers.get_images(train)
X_test = helpers.get_images(test)

y = to_categorical(train.is_iceberg.values,num_classes=2)

ids = test["id"]

In [89]:
trainRunner = Trainer(ids, X, y, X_test, [
    DaveModel(ids),
    DaveVGG(ids),
    DaveVGG19(ids),
    LeNetModel(ids),
    BestModel(ids)
])

In [90]:
label_maker = PseudoLabeller(trainRunner)



Model: davemodel
Batch Size: 32
Epochs: 50
Epoch 1/50
41/40 [==============================] - 4s - loss: 0.5788 - acc: 0.7038 - val_loss: 0.6754 - val_acc: 0.6573
Epoch 2/50
41/40 [==============================] - 1s - loss: 0.5039 - acc: 0.7393 - val_loss: 0.6410 - val_acc: 0.6573
Epoch 3/50
41/40 [==============================] - 1s - loss: 0.4743 - acc: 0.7644 - val_loss: 0.6493 - val_acc: 0.6573
Epoch 4/50
41/40 [==============================] - 1s - loss: 0.4491 - acc: 0.7709 - val_loss: 0.7121 - val_acc: 0.6573
Epoch 5/50
41/40 [==============================] - 1s - loss: 0.4021 - acc: 0.8032 - val_loss: 0.7779 - val_acc: 0.6573
Epoch 6/50
41/40 [==============================] - 1s - loss: 0.3898 - acc: 0.8124 - val_loss: 0.7852 - val_acc: 0.6573
Epoch 7/50
41/40 [==============================] - 1s - loss: 0.3661 - acc: 0.8197 - val_loss: 1.0326 - val_acc: 0.6573
Epoch 8/50
41/40 [==============================] - 2s - loss: 0.3586 - acc: 0.8308 - val_loss: 1.1484 - val

41/40 [==============================] - 5s - loss: 0.5310 - acc: 0.7152 - val_loss: 0.5710 - val_acc: 0.6137
Epoch 17/50
41/40 [==============================] - 5s - loss: 0.5413 - acc: 0.7171 - val_loss: 0.5565 - val_acc: 0.6075
Epoch 18/50
41/40 [==============================] - 5s - loss: 0.5096 - acc: 0.7579 - val_loss: 0.6273 - val_acc: 0.6355
Epoch 19/50
41/40 [==============================] - 5s - loss: 0.4870 - acc: 0.7598 - val_loss: 0.4743 - val_acc: 0.7352
Epoch 20/50
41/40 [==============================] - 5s - loss: 0.4379 - acc: 0.7953 - val_loss: 0.4762 - val_acc: 0.7601
Epoch 21/50
41/40 [==============================] - 5s - loss: 0.4305 - acc: 0.7930 - val_loss: 0.3714 - val_acc: 0.8100
Epoch 22/50
41/40 [==============================] - 5s - loss: 0.4126 - acc: 0.8022 - val_loss: 0.4117 - val_acc: 0.8193
Epoch 23/50
41/40 [==============================] - 5s - loss: 0.4450 - acc: 0.7930 - val_loss: 0.4201 - val_acc: 0.8069
Epoch 24/50
41/40 [=================

41/40 [==============================] - 6s - loss: 0.3397 - acc: 0.8444 - val_loss: 0.4166 - val_acc: 0.7882
Epoch 33/50
41/40 [==============================] - 6s - loss: 0.3456 - acc: 0.8254 - val_loss: 0.3853 - val_acc: 0.8629
Epoch 34/50
41/40 [==============================] - 6s - loss: 0.3285 - acc: 0.8551 - val_loss: 0.3366 - val_acc: 0.8536
Epoch 35/50
41/40 [==============================] - 6s - loss: 0.3205 - acc: 0.8426 - val_loss: 0.3942 - val_acc: 0.8037
Epoch 36/50
41/40 [==============================] - 6s - loss: 0.3335 - acc: 0.8452 - val_loss: 0.4288 - val_acc: 0.7819
Epoch 37/50
41/40 [==============================] - 6s - loss: 0.3487 - acc: 0.8655 - val_loss: 0.3919 - val_acc: 0.8006
Epoch 38/50
41/40 [==============================] - 6s - loss: 0.4630 - acc: 0.7999 - val_loss: 0.3879 - val_acc: 0.8287
Epoch 39/50
41/40 [==============================] - 6s - loss: 0.3245 - acc: 0.8391 - val_loss: 0.3344 - val_acc: 0.9097
Epoch 40/50
41/40 [=================

41/40 [==============================] - 1s - loss: 0.3051 - acc: 0.8589 - val_loss: 0.3144 - val_acc: 0.8692
Epoch 49/50
41/40 [==============================] - 1s - loss: 0.3039 - acc: 0.8582 - val_loss: 0.4072 - val_acc: 0.7913
Epoch 50/50
41/40 [==============================] - 1s - loss: 0.3193 - acc: 0.8471 - val_loss: 0.3633 - val_acc: 0.8318


Model: best
Batch Size: 32
Epochs: 50
Epoch 1/50
41/40 [==============================] - 2s - loss: 0.6883 - acc: 0.5258 - val_loss: 0.6919 - val_acc: 0.4330
Epoch 2/50
41/40 [==============================] - 1s - loss: 0.6708 - acc: 0.5631 - val_loss: 0.6771 - val_acc: 0.6573
Epoch 3/50
41/40 [==============================] - 1s - loss: 0.6738 - acc: 0.5704 - val_loss: 0.6900 - val_acc: 0.5016
Epoch 4/50
41/40 [==============================] - 1s - loss: 0.6213 - acc: 0.6530 - val_loss: 0.6233 - val_acc: 0.6262
Epoch 5/50
41/40 [==============================] - 1s - loss: 0.5953 - acc: 0.7041 - val_loss: 0.6242 - val_acc: 0.5981
E

In [92]:
label_maker.results.head()

ids  definitive  davemodel       vgg     vgg19     lenet      best  \
0  5941774d       False   0.609118  0.338854  0.443578  0.642698  0.654271   
1  4023181e       False   0.496923  0.343355  0.950608  0.552938  0.778422   
2  b20200e4       False   0.999873  0.388912  1.000000  0.997846  0.998998   
3  e7f018bb        True   0.001376  0.032233  0.001072  0.001706  0.027113   
4  4371c8c3        True   0.994152  0.525234  0.965022  0.552247  0.783079   

   label  
0      1  
1      1  
2      1  
3      0  
4      1

In [93]:
print(label_maker.trainer.X_train.shape)
print(label_maker.trainer.y_train.shape)

X_train_pseudo = label_maker.trainer.X_test[label_maker.results["definitive"]]
y_train_pseudo = label_maker.results[label_maker.results["definitive"]]["label"]

print(X_train_pseudo.shape)

new_train_y = []

for record in y_train_pseudo:
    if record == 0:
        new_train_y.append([0., 1.])
    elif record == 1:
        new_train_y.append([1., 0.])
        
y_train_pseudo = np.array(new_train_y)

print(y_train_pseudo.shape)

# Add definitive data to original training data
orig_train = label_maker.trainer.X_train.copy()
X_train_pseudo = np.append(orig_train, X_train_pseudo, axis = 0)

orig_labels = label_maker.trainer.y_train.copy()
y_train_pseudo = np.append(orig_labels, y_train_pseudo, axis = 0)

print(X_train_pseudo.shape)
print(y_train_pseudo.shape)

# anotherRunner = Trainer(ids, X_train_pseudo, y_train_pseudo, X_test, [
#     DaveModel(ids),
#     DaveVGG(ids),
#     DaveVGG19(ids),
#     LeNetModel(ids),
#     BestModel(ids)
# ])



(1283, 75, 75, 3)
(1283, 2)
(4106, 75, 75, 3)
(4106, 2)
(5389, 75, 75, 3)
(5389, 2)


In [94]:
best = BestModel(ids)
best.train(X_train_pseudo, y_train_pseudo, label_maker.trainer.X_val, label_maker.trainer.y_val, epochs = 50)



Model: best
Batch Size: 32
Epochs: 50
Epoch 1/50
169/168 [==============================] - 8s - loss: 0.4164 - acc: 0.7987 - val_loss: 0.5991 - val_acc: 0.6573
Epoch 2/50
169/168 [==============================] - 7s - loss: 0.2711 - acc: 0.8892 - val_loss: 0.5738 - val_acc: 0.7103
Epoch 3/50
169/168 [==============================] - 7s - loss: 0.2044 - acc: 0.9211 - val_loss: 0.4486 - val_acc: 0.7757
Epoch 4/50
169/168 [==============================] - 7s - loss: 0.1791 - acc: 0.9347 - val_loss: 0.7519 - val_acc: 0.6885
Epoch 5/50
169/168 [==============================] - 7s - loss: 0.1675 - acc: 0.9384 - val_loss: 0.4556 - val_acc: 0.8100
Epoch 6/50
169/168 [==============================] - 7s - loss: 0.1880 - acc: 0.9318 - val_loss: 0.5175 - val_acc: 0.7819
Epoch 7/50
169/168 [==============================] - 7s - loss: 0.1584 - acc: 0.9442 - val_loss: 0.4197 - val_acc: 0.8287
Epoch 8/50
169/168 [==============================] - 7s - loss: 0.1533 - acc: 0.9446 - val_loss: 0

In [ ]:
label_maker

In [ ]:
# trainRunner.train(32, 1, False)
# trainRunner.train_full(32, 1, False)


In [17]:
trainRunner.predict()

In [18]:
trainRunner.predictions

[array([[ 0.58547407,  0.41452599],
        [ 0.57440114,  0.42559892],
        [ 0.60632485,  0.39367515],
        ..., 
        [ 0.59274668,  0.4072533 ],
        [ 0.59482783,  0.40517214],
        [ 0.62089276,  0.37910724]], dtype=float32),
 array([[ 0.51180393,  0.48819605],
        [ 0.51168621,  0.48831385],
        [ 0.51210481,  0.48789516],
        ..., 
        [ 0.5117113 ,  0.4882887 ],
        [ 0.51172554,  0.48827448],
        [ 0.51198667,  0.48801333]], dtype=float32),
 array([[ 0.50135714,  0.49864292],
        [ 0.50138915,  0.49861091],
        [ 0.96230453,  0.03769542],
        ..., 
        [ 0.50137621,  0.49862379],
        [ 0.50154185,  0.49845815],
        [ 0.50160444,  0.49839562]], dtype=float32),
 array([[ 0.24273774,  0.75726223],
        [ 0.35269514,  0.64730477],
        [ 0.88178951,  0.11821055],
        ..., 
        [ 0.28946409,  0.71053594],
        [ 0.28727075,  0.71272928],
        [ 0.50449407,  0.4955059 ]], dtype=float32)]