In [29]:
%load_ext autoreload
%autoreload 2

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import pdb
from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical
from keras import backend as K
from matplotlib import pyplot as plt
%matplotlib inline
import scipy
from scipy import misc, ndimage
from scipy.ndimage.interpolation import zoom
from scipy.ndimage import imread
import helpers
from models import DaveModel, DaveVGG, DaveVGG19, SimpleModel, LeNetModel
from trainer import Trainer
from labeller import PseudoLabeller

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
train = pd.read_json("_RawData/train.json/data/processed/train.json")
test = pd.read_json("_RawData/test.json/data/processed/test.json")

X = helpers.get_images(train)
X_test = helpers.get_images(test)

y = to_categorical(train.is_iceberg.values,num_classes=2)

ids = test["id"]

In [23]:
trainRunner = Trainer(ids, X, y, X_test, [
    DaveModel(ids),
    DaveVGG(ids),
    DaveVGG19(ids),
    LeNetModel(ids)
])

In [35]:
label_maker = PseudoLabeller(trainRunner)

davemodel
vgg
vgg19
lenet
           ids  definitive  davemodel       vgg     vgg19     lenet
0     5941774d       False   0.551755  0.510289  0.244644  0.428729
1     4023181e       False   0.549825  0.510284  0.351416  0.633797
2     b20200e4        True   0.567553  0.510288  0.536220  0.915371
3     e7f018bb        True   0.549922  0.510322  0.545917  0.552448
4     4371c8c3        True   0.550571  0.510288  0.538486  0.801753
5     a8d9b1fd       False   0.553152  0.510322  0.465313  0.551165
6     29e7727e        True   0.556170  0.510319  0.543129  0.568605
7     92a51ffb       False   0.549017  0.510311  0.379246  0.418413
8     c769ac97        True   0.564719  0.510324  0.542371  0.686537
9     aee0547d        True   0.565349  0.510313  0.534481  0.759206
10    565b28ac        True   0.569082  0.510322  0.536045  0.930691
11    e04e9775       False   0.553112  0.510298  0.442186  0.602359
12    8e8161d1        True   0.563846  0.510342  0.553643  0.740052
13    4cf4d256        

In [16]:
# trainRunner.train(32, 1, False)
trainRunner.train_full(32, 1, False)




Model: davemodel
Batch Size: 32
Epochs: 1
Epoch 1/1
51/50 [==============================] - 5s - loss: 0.5770 - acc: 0.6930     


Model: vgg
Batch Size: 32
Epochs: 1
Epoch 1/1
51/50 [==============================] - 8s - loss: 0.6850 - acc: 0.5123     


Model: vgg19
Batch Size: 32
Epochs: 1
Epoch 1/1
51/50 [==============================] - 8s - loss: 0.6746 - acc: 0.5300     


Model: lenet
Batch Size: 32
Epochs: 1
Epoch 1/1
51/50 [==============================] - 2s - loss: 0.6647 - acc: 0.5865     


In [17]:
trainRunner.predict()

In [18]:
trainRunner.predictions

[array([[ 0.58547407,  0.41452599],
        [ 0.57440114,  0.42559892],
        [ 0.60632485,  0.39367515],
        ..., 
        [ 0.59274668,  0.4072533 ],
        [ 0.59482783,  0.40517214],
        [ 0.62089276,  0.37910724]], dtype=float32),
 array([[ 0.51180393,  0.48819605],
        [ 0.51168621,  0.48831385],
        [ 0.51210481,  0.48789516],
        ..., 
        [ 0.5117113 ,  0.4882887 ],
        [ 0.51172554,  0.48827448],
        [ 0.51198667,  0.48801333]], dtype=float32),
 array([[ 0.50135714,  0.49864292],
        [ 0.50138915,  0.49861091],
        [ 0.96230453,  0.03769542],
        ..., 
        [ 0.50137621,  0.49862379],
        [ 0.50154185,  0.49845815],
        [ 0.50160444,  0.49839562]], dtype=float32),
 array([[ 0.24273774,  0.75726223],
        [ 0.35269514,  0.64730477],
        [ 0.88178951,  0.11821055],
        ..., 
        [ 0.28946409,  0.71053594],
        [ 0.28727075,  0.71272928],
        [ 0.50449407,  0.4955059 ]], dtype=float32)]