In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import pdb
from sklearn.model_selection import train_test_split
from keras.utils.np_utils import to_categorical
from keras import backend as K
from matplotlib import pyplot as plt
%matplotlib inline
import scipy
from scipy import misc, ndimage
from scipy.ndimage.interpolation import zoom
from scipy.ndimage import imread
import helpers
from models import DaveModel, DaveVGG, DaveVGG19, SimpleModel, LeNetModel
from trainer import Trainer

Using TensorFlow backend.


In [2]:
train = pd.read_json("_RawData/train.json/data/processed/train.json")
test = pd.read_json("_RawData/test.json/data/processed/test.json")

X = helpers.get_images(train)
X_test = helpers.get_images(test)

y = to_categorical(train.is_iceberg.values,num_classes=2)

ids = test["id"]

In [11]:
trainRunner = Trainer(ids, X, y, [
    DaveModel(ids),
    DaveVGG(ids),
    DaveVGG19(ids),
    LeNetModel(ids)
])

In [12]:
# trainRunner.train(32, 1, False)
trainRunner.train_full(32, 1, False)




Model: davemodel
Batch Size: 32
Epochs: 1
Epoch 1/1
51/50 [==============================] - 3s - loss: 0.5531 - acc: 0.7126     


Model: vgg
Batch Size: 32
Epochs: 1
Epoch 1/1
51/50 [==============================] - 8s - loss: 0.6887 - acc: 0.5178     


Model: vgg19
Batch Size: 32
Epochs: 1
Epoch 1/1
51/50 [==============================] - 8s - loss: 0.6930 - acc: 0.5258     


Model: lenet
Batch Size: 32
Epochs: 1
Epoch 1/1
51/50 [==============================] - 2s - loss: 0.6744 - acc: 0.6047     


In [13]:
trainRunner.predict(X_test)

In [14]:
trainRunner.predictions

[array([[ 0.46230322,  0.53769678],
        [ 0.46604916,  0.53395075],
        [ 0.4575015 ,  0.54249853],
        ..., 
        [ 0.45932385,  0.54067612],
        [ 0.45786059,  0.54213941],
        [ 0.45556942,  0.54443055]], dtype=float32),
 array([[ 0.5057869 ,  0.4942131 ],
        [ 0.69722164,  0.30277836],
        [ 0.85135168,  0.14864834],
        ..., 
        [ 0.50723886,  0.49276114],
        [ 0.50646132,  0.49353865],
        [ 0.64603692,  0.35396308]], dtype=float32),
 array([[ 0.51047188,  0.48952809],
        [ 0.51094073,  0.48905921],
        [ 0.51345146,  0.48654848],
        ..., 
        [ 0.51019639,  0.48980364],
        [ 0.51085556,  0.48914438],
        [ 0.51018059,  0.48981938]], dtype=float32),
 array([[ 0.27341908,  0.72658086],
        [ 0.34210107,  0.65789896],
        [ 0.6335004 ,  0.3664996 ],
        ..., 
        [ 0.29279649,  0.70720351],
        [ 0.31360942,  0.68639052],
        [ 0.49054417,  0.50945592]], dtype=float32)]